server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: synapse-ingestion-api
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/synapse}
    username: ${DATABASE_USERNAME:synapse}
    password: ${DATABASE_PASSWORD:synapse}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1800000
  
  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.synapse: DEBUG
    org.springframework.web: INFO
    org.springframework.jdbc: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"